### ISSUE TITLE
Including `micronaut-cache-management` breaks GraalVM native image

### ISSUE THREAD

**Issue by sgammon** [micronaut-projects/micronaut-cache#691]
### Expected Behavior

Including `micronaut-cache-management` in an app should not break it

### Actual Behaviour

It seems to break the native build :(

```
========================================================================================================================
GraalVM Native Image: Generating 'buildless.dbg' (executable)...
========================================================================================================================
For detailed information and explanations on the build output, visit:
https://github.com/oracle/graal/blob/master/docs/reference-manual/native-image/BuildOutput.md
------------------------------------------------------------------------------------------------------------------------
Warning: Feature class com.google.cloud.nativeimage.features.spring.SpringTraceFeature is annotated with the deprecated annotation @AutomaticFeature. Support for this annotation will be removed in a future version of GraalVM. Applications should register a feature using the option --features=com.google.cloud.nativeimage.features.spring.SpringTraceFeature
Warning: Feature class com.google.cloud.nativeimage.features.SpannerFeature is annotated with the deprecated annotation @AutomaticFeature. Support for this annotation will be removed in a future version of GraalVM. Applications should register a feature using the option --features=com.google.cloud.nativeimage.features.SpannerFeature
Warning: Feature class com.google.cloud.nativeimage.features.core.GrpcNettyFeature is annotated with the deprecated annotation @AutomaticFeature. Support for this annotation will be removed in a future version of GraalVM. Applications should register a feature using the option --features=com.google.cloud.nativeimage.features.core.GrpcNettyFeature
Warning: Feature class com.google.cloud.nativeimage.features.core.OpenCensusFeature is annotated with the deprecated annotation @AutomaticFeature. Support for this annotation will be removed in a future version of GraalVM. Applications should register a feature using the option --features=com.google.cloud.nativeimage.features.core.OpenCensusFeature
Warning: Feature class com.google.cloud.nativeimage.features.core.GoogleJsonClientFeature is annotated with the deprecated annotation @AutomaticFeature. Support for this annotation will be removed in a future version of GraalVM. Applications should register a feature using the option --features=com.google.cloud.nativeimage.features.core.GoogleJsonClientFeature
Warning: Feature class com.google.cloud.nativeimage.features.cloudfunctions.CloudFunctionsFeature is annotated with the deprecated annotation @AutomaticFeature. Support for this annotation will be removed in a future version of GraalVM. Applications should register a feature using the option --features=com.google.cloud.nativeimage.features.cloudfunctions.CloudFunctionsFeature
Warning: Feature class com.google.cloud.nativeimage.features.gcp.CloudSqlFeature is annotated with the deprecated annotation @AutomaticFeature. Support for this annotation will be removed in a future version of GraalVM. Applications should register a feature using the option --features=com.google.cloud.nativeimage.features.gcp.CloudSqlFeature
# Printing Dashboard BGV dump header to: /Volumes/VAULTROOM/elide/apps/buildless/packages/cli/build/native/nativeCompile/cli.bgv
Warning: Using -g is not supported on macOS
[1/8] Initializing...                                                                                   (13.4s @ 0.32GB)
 Java version: 21.0.1+12, vendor version: Oracle GraalVM 21.0.1+12.1
 Graal compiler: optimization level: b, target machine: armv8-a, PGO: off
 C compiler: cc (apple, arm64, 15.0.0)
 Garbage collector: Serial GC (max heap size: 80% of RAM)
 11 user-specific feature(s):
 - com.google.cloud.nativeimage.features.SpannerFeature
 - com.google.cloud.nativeimage.features.cloudfunctions.CloudFunctionsFeature
 - com.google.cloud.nativeimage.features.core.GoogleJsonClientFeature
 - com.google.cloud.nativeimage.features.core.GrpcNettyFeature
 - com.google.cloud.nativeimage.features.core.OpenCensusFeature
 - com.google.cloud.nativeimage.features.gcp.CloudSqlFeature
 - com.google.cloud.nativeimage.features.spring.SpringTraceFeature
 - com.oracle.svm.thirdparty.gson.GsonFeature
 - io.micronaut.cache.caffeine.graal.CaffeineFeature
 - io.micronaut.core.io.service.ServiceLoaderFeature
 - io.micronaut.jackson.JacksonDatabindFeature
------------------------------------------------------------------------------------------------------------------------
 7 experimental option(s) unlocked:
 - '-H:CStandard' (origin(s): command line)
 - '-H:-DeleteLocalSymbols' (origin(s): command line)
 - '-H:IncludeResourceBundles' (origin(s): command line)
 - '-H:+DashboardAll' (origin(s): command line)
 - '-H:+UseContainerSupport' (origin(s): command line)
 - '-H:+SourceLevelDebug' (origin(s): command line)
 - '-H:DashboardDump' (origin(s): command line)
------------------------------------------------------------------------------------------------------------------------
Build resources:
 - 21.33GB of memory (22.2% of 96.00GB system memory, set via '-Xmx24G')
 - 12 thread(s) (100.0% of 12 available processor(s), determined at start)
# Printing 1 class initialization trace(s) of class(es) traced by TraceClassInitialization to: /Volumes/VAULTROOM/elide/apps/buildless/packages/cli/build/native/nativeCompile/reports/traced_class_initialization_20231114_131537.txt
[2/8] Performing analysis...  [******]                                                                  (44.8s @ 2.75GB)
   26,027 reachable types   (91.5% of   28,438 total)
   43,240 reachable fields  (66.3% of   65,229 total)
  157,358 reachable methods (64.7% of  243,339 total)
    9,159 types, 4,519 fields, and 17,632 methods registered for reflection
      166 types,   231 fields, and   185 methods registered for JNI access
        5 native libraries: -framework CoreServices, -framework Foundation, dl, pthread, z
# Printing Dashboard PointsTo analysis BGV dump to: /Volumes/VAULTROOM/elide/apps/buildless/packages/cli/build/native/nativeCompile/cli.bgv
Print of Dashboard dump output ended.

Error: Unsupported features in 2 methods
Detailed message:
Error: Detected a byte[] in the image heap that contains a user directory. This means that file system information from the native image build is persisted and available at image runtime, which is most likely an error.
byte[] that is problematic: /Library/Java/JavaVirtualMachines/gvm.jdk21/Contents/Home/conf/chronology
Disallowed substring with user directory: /Library/Java/JavaVirtualMachines/gvm.jdk21/Contents/Home
This check can be disabled using the option -H:-DetectUserDirectoriesInImageHeap
Trace: Object was reached by
------------------------------------------------------------------------------------------------------------------------
  reading field sun.nio.fs.UnixPath.path of constant 
    sun.nio.fs.UnixPath@4f1304f6: /Library/Java/JavaVirtualMachines/gvm.jdk21/Contents/Home/conf/chronology
  scanning root sun.nio.fs.UnixPath@4f1304f6: /Library/Java/JavaVirtualMachines/gvm.jdk21/Contents/Home/conf/chronology embedded in 
    java.time.chrono.HijrahChronology.lambda$readConfigProperties$2(HijrahChronology.java:831)
  parsing method java.time.chrono.HijrahChronology.lambda$readConfigProperties$2(HijrahChronology.java:831) reachable via the parsing context
    at java.time.chrono.HijrahChronology$$Lambda/0x000000f802eef760.run(Unknown Source)
    at com.oracle.svm.core.jdk.Target_java_security_AccessController.executePrivileged(SecuritySubstitutions.java:129)
    at apple.security.AppleProvider.<init>(AppleProvider.java:82)
    at com.oracle.svm.core.code.FactoryMethodHolder.AppleProvider_constructor_6be760ede53594c014cd466f96a8607eb153477a(generated:0)
    at static root method.(Unknown Source)

Error: Detected a string in the image heap that contains a user directory. This means that file system information from the native image build is persisted and available at image runtime, which is most likely an error.
String that is problematic: /Library/Java/JavaVirtualMachines/gvm.jdk21/Contents/Home/conf/chronology
Disallowed substring with user directory: /Library/Java/JavaVirtualMachines/gvm.jdk21/Contents/Home
This check can be disabled using the option -H:-DetectUserDirectoriesInImageHeap
Trace: Object was reached by
  reading field sun.nio.fs.UnixPath.stringValue of constant 
    sun.nio.fs.UnixPath@4f1304f6: /Library/Java/JavaVirtualMachines/gvm.jdk21/Contents/Home/conf/chronology
  scanning root sun.nio.fs.UnixPath@4f1304f6: /Library/Java/JavaVirtualMachines/gvm.jdk21/Contents/Home/conf/chronology embedded in 
    java.time.chrono.HijrahChronology.lambda$readConfigProperties$2(HijrahChronology.java:831)
  parsing method java.time.chrono.HijrahChronology.lambda$readConfigProperties$2(HijrahChronology.java:831) reachable via the parsing context
    at java.time.chrono.HijrahChronology$$Lambda/0x000000f802eef760.run(Unknown Source)
    at com.oracle.svm.core.jdk.Target_java_security_AccessController.executePrivileged(SecuritySubstitutions.java:129)
    at apple.security.AppleProvider.<init>(AppleProvider.java:82)
    at com.oracle.svm.core.code.FactoryMethodHolder.AppleProvider_constructor_6be760ede53594c014cd466f96a8607eb153477a(generated:0)
    at static root method.(Unknown Source)


com.oracle.svm.core.util.UserError$UserException: Unsupported features in 2 methods
Detailed message:
Error: Detected a byte[] in the image heap that contains a user directory. This means that file system information from the native image build is persisted and available at image runtime, which is most likely an error.
byte[] that is problematic: /Library/Java/JavaVirtualMachines/gvm.jdk21/Contents/Home/conf/chronology
Disallowed substring with user directory: /Library/Java/JavaVirtualMachines/gvm.jdk21/Contents/Home
This check can be disabled using the option -H:-DetectUserDirectoriesInImageHeap
Trace: Object was reached by
  reading field sun.nio.fs.UnixPath.path of constant 
    sun.nio.fs.UnixPath@4f1304f6: /Library/Java/JavaVirtualMachines/gvm.jdk21/Contents/Home/conf/chronology
  scanning root sun.nio.fs.UnixPath@4f1304f6: /Library/Java/JavaVirtualMachines/gvm.jdk21/Contents/Home/conf/chronology embedded in 
    java.time.chrono.HijrahChronology.lambda$readConfigProperties$2(HijrahChronology.java:831)
  parsing method java.time.chrono.HijrahChronology.lambda$readConfigProperties$2(HijrahChronology.java:831) reachable via the parsing context
    at java.time.chrono.HijrahChronology$$Lambda/0x000000f802eef760.run(Unknown Source)
    at com.oracle.svm.core.jdk.Target_java_security_AccessController.executePrivileged(SecuritySubstitutions.java:129)
    at apple.security.AppleProvider.<init>(AppleProvider.java:82)
    at com.oracle.svm.core.code.FactoryMethodHolder.AppleProvider_constructor_6be760ede53594c014cd466f96a8607eb153477a(generated:0)
    at static root method.(Unknown Source)

Error: Detected a string in the image heap that contains a user directory. This means that file system information from the native image build is persisted and available at image runtime, which is most likely an error.
String that is problematic: /Library/Java/JavaVirtualMachines/gvm.jdk21/Contents/Home/conf/chronology
Disallowed substring with user directory: /Library/Java/JavaVirtualMachines/gvm.jdk21/Contents/Home
This check can be disabled using the option -H:-DetectUserDirectoriesInImageHeap
Trace: Object was reached by
  reading field sun.nio.fs.UnixPath.stringValue of constant 
    sun.nio.fs.UnixPath@4f1304f6: /Library/Java/JavaVirtualMachines/gvm.jdk21/Contents/Home/conf/chronology
  scanning root sun.nio.fs.UnixPath@4f1304f6: /Library/Java/JavaVirtualMachines/gvm.jdk21/Contents/Home/conf/chronology embedded in 
    java.time.chrono.HijrahChronology.lambda$readConfigProperties$2(HijrahChronology.java:831)
  parsing method java.time.chrono.HijrahChronology.lambda$readConfigProperties$2(HijrahChronology.java:831) reachable via the parsing context
    at java.time.chrono.HijrahChronology$$Lambda/0x000000f802eef760.run(Unknown Source)
    at com.oracle.svm.core.jdk.Target_java_security_AccessController.executePrivileged(SecuritySubstitutions.java:129)
    at apple.security.AppleProvider.<init>(AppleProvider.java:82)
    at com.oracle.svm.core.code.FactoryMethodHolder.AppleProvider_constructor_6be760ede53594c014cd466f96a8607eb153477a(generated:0)
    at static root method.(Unknown Source)


        at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.UserError.abort(UserError.java:85)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.FallbackFeature.reportAsFallback(FallbackFeature.java:248)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:814)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:592)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:550)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:538)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:720)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.start(NativeImageGeneratorRunner.java:142)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:97)
Caused by: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: Unsupported features in 2 methods
Detailed message:
Error: Detected a byte[] in the image heap that contains a user directory. This means that file system information from the native image build is persisted and available at image runtime, which is most likely an error.
byte[] that is problematic: /Library/Java/JavaVirtualMachines/gvm.jdk21/Contents/Home/conf/chronology
Disallowed substring with user directory: /Library/Java/JavaVirtualMachines/gvm.jdk21/Contents/Home
This check can be disabled using the option -H:-DetectUserDirectoriesInImageHeap
Trace: Object was reached by
  reading field sun.nio.fs.UnixPath.path of constant 
    sun.nio.fs.UnixPath@4f1304f6: /Library/Java/JavaVirtualMachines/gvm.jdk21/Contents/Home/conf/chronology
  scanning root sun.nio.fs.UnixPath@4f1304f6: /Library/Java/JavaVirtualMachines/gvm.jdk21/Contents/Home/conf/chronology embedded in 
    java.time.chrono.HijrahChronology.lambda$readConfigProperties$2(HijrahChronology.java:831)
  parsing method java.time.chrono.HijrahChronology.lambda$readConfigProperties$2(HijrahChronology.java:831) reachable via the parsing context
    at java.time.chrono.HijrahChronology$$Lambda/0x000000f802eef760.run(Unknown Source)
    at com.oracle.svm.core.jdk.Target_java_security_AccessController.executePrivileged(SecuritySubstitutions.java:129)
    at apple.security.AppleProvider.<init>(AppleProvider.java:82)
    at com.oracle.svm.core.code.FactoryMethodHolder.AppleProvider_constructor_6be760ede53594c014cd466f96a8607eb153477a(generated:0)
    at static root method.(Unknown Source)

Error: Detected a string in the image heap that contains a user directory. This means that file system information from the native image build is persisted and available at image runtime, which is most likely an error.
String that is problematic: /Library/Java/JavaVirtualMachines/gvm.jdk21/Contents/Home/conf/chronology
Disallowed substring with user directory: /Library/Java/JavaVirtualMachines/gvm.jdk21/Contents/Home
This check can be disabled using the option -H:-DetectUserDirectoriesInImageHeap
Trace: Object was reached by
  reading field sun.nio.fs.UnixPath.stringValue of constant 
    sun.nio.fs.UnixPath@4f1304f6: /Library/Java/JavaVirtualMachines/gvm.jdk21/Contents/Home/conf/chronology
  scanning root sun.nio.fs.UnixPath@4f1304f6: /Library/Java/JavaVirtualMachines/gvm.jdk21/Contents/Home/conf/chronology embedded in 
    java.time.chrono.HijrahChronology.lambda$readConfigProperties$2(HijrahChronology.java:831)
  parsing method java.time.chrono.HijrahChronology.lambda$readConfigProperties$2(HijrahChronology.java:831) reachable via the parsing context
    at java.time.chrono.HijrahChronology$$Lambda/0x000000f802eef760.run(Unknown Source)
    at com.oracle.svm.core.jdk.Target_java_security_AccessController.executePrivileged(SecuritySubstitutions.java:129)
    at apple.security.AppleProvider.<init>(AppleProvider.java:82)
    at com.oracle.svm.core.code.FactoryMethodHolder.AppleProvider_constructor_6be760ede53594c014cd466f96a8607eb153477a(generated:0)
    at static root method.(Unknown Source)


        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.constraints.UnsupportedFeatures.report(UnsupportedFeatures.java:129)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:809)
        ... 6 more
                       8.5s (11.9% of total time) in 148 GCs | Peak RSS: 7.80GB | CPU load: 5.06
========================================================================================================================
```

### Steps To Reproduce

1. Generate Micronaut app which uses `micronaut-cache` and GraalVM
2. Add the `micronaut-cache-management` dependency
3. Build native, observe error

### Environment Information

- Operating System: macOS Ventura 13.5.1
- JVM (build-time):
```
java version "20.0.2" 2023-07-18
Java(TM) SE Runtime Environment Oracle GraalVM 20.0.2+9.1 (build 20.0.2+9-jvmci-23.0-b14)
Java HotSpot(TM) 64-Bit Server VM Oracle GraalVM 20.0.2+9.1 (build 20.0.2+9-jvmci-23.0-b14, mixed mode, sharing)
```
- GVM (native build time):
```
java version "21.0.1" 2023-10-17
Java(TM) SE Runtime Environment Oracle GraalVM 21.0.1+12.1 (build 21.0.1+12-jvmci-23.1-b19)
Java HotSpot(TM) 64-Bit Server VM Oracle GraalVM 21.0.1+12.1 (build 21.0.1+12-jvmci-23.1-b19, mixed mode, sharing)
```

### Version

4.1.6

**Comment by sgammon** [comment]
Well, a repro which added `micronaut-cache-management` seems to build fine via Micronaut Launch. I'll keep trying to isolate this issue, but it only surfaces in our application when we add that dependency.

**Comment by sdelamo** [comment]
closing this for now @sgammon please, reopen if you have a reproducer.
